<a href="https://colab.research.google.com/github/dinesh-kushwaha/ai-ml/blob/main/ml-template-base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Processing Tools**

importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [ ]:
dataset=pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 nan]
 ['Spain' nan 54000.0]
 ['France' nan 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## **Taking care of missing data**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]= imputer.transform(X[:,1:3])

In [ ]:
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0      NaN       Yes
6    Spain   NaN  54000.0        No
7   France   NaN  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 64750.0]
 [0.0 1.0 0.0 0.0 35.0 64750.0]
 [1.0 0.0 0.0 1.0 37.625 54000.0]
 [0.0 1.0 0.0 0.0 37.625 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 64750.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 64750.0]
 [0.0 1.0 0.0 0.0 1.0 37.625 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.625 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


## Encode the dependent variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Split the dataset into training and test data

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
print(X_train)

[[0.0 1.0 0.0 0.0 1.0 37.625 54000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 64750.0]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 37.625 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 64750.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Featue scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

In [ ]:
print(X_train)

[[0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -0.1654410748263605
  -1.0619485894476408]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834 0.21557473386465156
  -0.09551918529423226]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 0.8572855695547771
  0.5562587849487642]
 [0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -0.10528068398041122
  -0.4326457216268167]
 [0.0 1.0 0.0 -0.5773502691896258 1.2909944487358056 -1.8699854821282564
  -1.601351047579776]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 -0.1654410748263605
  1.1855616527695885]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834 1.8198518230899654
  1.5451632915243452]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7745966692414834 -0.5865638107480055
  -0.09551918529423226]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 1.0 -1.0 0.0 1.0 1.0]]
